#video = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\video.avi'
image = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\2d'
ply = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\ply'
json = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\json'
ply_data = r'C:\Users\exley\OneDrive\Documents\GitHub\DeepPoseRobot\robotpose\ply_data.pyc'

skeleton_mult = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\mult_skeleton.csv'
model_mult = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\model_LEAP_mult.h5'
ds_mult = r'C:\Users\exley\OneDrive - The Ohio State University\CDME\RobotPose\data\mult_ds.h5'

datasets = r'data/'
skeletons = r'data/skeletons'
models = r'models/'
seg_models = r'models/segmentation'
video = r'output/video.avi'